data:extend({
	{
		type = "cargo-wagon",
		name = "yir_4a_container_cr",
		icon = "__z_yira_american__/graphics/icons/4a_container_icon.png",
		icon_size = 64,
		inventory_size = 30,
		max_health = 600,
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		connection_distance = 3, 
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.5,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.5,
	},

	{
		type = "cargo-wagon",
		name = "yir_4a_clean_cr",
		icon = "__z_yira_american__/graphics/icons/4a_cr_icon.png",
		icon_size = 64,
		inventory_size = 30,
		max_health = 600,
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		connection_distance = 3, 
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.5,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.5,
	},

	{
		type = "cargo-wagon",
		name = "yir_wagon_caboose_cr",
		icon = "__z_yira_american__/graphics/icons/2a_caboose_icon.png",
		icon_size = 64,
		inventory_size = 5,
		max_health = 400,
		collision_box = {{-0.6, -1.5}, {0.6, 1.5}},
		selection_box = {{-1, -2}, {1, 2}},
		weight = 500,
		max_speed = 1.5,
		braking_force = 1,
		friction_force = 0.0015,
		air_resistance = 0.01,
		connection_distance = 3.6,
		joint_distance = 1.8,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.5,
	},
})